; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "OniPlayer"
#define MyAppVersion "6.0"
#define MyAppExeName "OniPlayer.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{84AAC02C-313F-424E-A9EA-6E3B59DE3442}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=OniPlayer
SetupIconFile=icon.ico
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\OniPlayer\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "controls.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "features.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "libvlc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "libvlccore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "plugins\*"; DestDir: "{app}/plugins"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "dist\OniPlayer\_internal\*"; DestDir: "{app}/_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "--reset-plugins-cache"; StatusMsg: "Building VLC plugins cache..."; Flags: runhidden
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent unchecked
Filename: "{app}\controls.txt"; Description: "View Controls"; Flags: postinstall skipifsilent unchecked shellexec

[Registry]
; Register application capabilities
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "Modern Video Player with Dark Theme"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "OniPlayer"
Root: HKLM; Subkey: "Software\RegisteredApplications"; ValueType: string; ValueName: "OniPlayer"; ValueData: "Software\OniPlayer\Capabilities"

; Register file associations for each video format
; MP4
Root: HKLM; Subkey: "Software\Classes\.mp4"; ValueType: string; ValueName: ""; ValueData: "OniPlayer.mp4"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mp4"; ValueType: string; ValueName: ""; ValueData: "OniPlayer Video File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mp4\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe,0"
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mp4\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\.mp4\OpenWithProgids"; ValueType: none; ValueName: "OniPlayer.mp4"
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".mp4"; ValueData: "OniPlayer.mp4"

; MKV
Root: HKLM; Subkey: "Software\Classes\.mkv"; ValueType: string; ValueName: ""; ValueData: "OniPlayer.mkv"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mkv"; ValueType: string; ValueName: ""; ValueData: "OniPlayer Video File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mkv\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe,0"
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mkv\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\.mkv\OpenWithProgids"; ValueType: none; ValueName: "OniPlayer.mkv"
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".mkv"; ValueData: "OniPlayer.mkv"

; AVI
Root: HKLM; Subkey: "Software\Classes\.avi"; ValueType: string; ValueName: ""; ValueData: "OniPlayer.avi"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.avi"; ValueType: string; ValueName: ""; ValueData: "OniPlayer Video File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.avi\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe,0"
Root: HKLM; Subkey: "Software\Classes\OniPlayer.avi\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\.avi\OpenWithProgids"; ValueType: none; ValueName: "OniPlayer.avi"
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".avi"; ValueData: "OniPlayer.avi"

; WebM
Root: HKLM; Subkey: "Software\Classes\.webm"; ValueType: string; ValueName: ""; ValueData: "OniPlayer.webm"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.webm"; ValueType: string; ValueName: ""; ValueData: "OniPlayer Video File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.webm\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe,0"
Root: HKLM; Subkey: "Software\Classes\OniPlayer.webm\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\.webm\OpenWithProgids"; ValueType: none; ValueName: "OniPlayer.webm"
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".webm"; ValueData: "OniPlayer.webm"

; Register application in App Paths
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\OniPlayer.exe"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\OniPlayer.exe"; ValueType: string; ValueName: "Path"; ValueData: "{app}"

; Register application for "Open with" dialog
Root: HKLM; Subkey: "Software\Classes\Applications\OniPlayer.exe\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\Applications\OniPlayer.exe"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "OniPlayer"


; Additional video formats
; MOV
Root: HKLM; Subkey: "Software\Classes\.mov"; ValueType: string; ValueName: ""; ValueData: "OniPlayer.mov"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mov"; ValueType: string; ValueName: ""; ValueData: "OniPlayer Video File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mov\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe,0"
Root: HKLM; Subkey: "Software\Classes\OniPlayer.mov\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\.mov\OpenWithProgids"; ValueType: none; ValueName: "OniPlayer.mov"
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".mov"; ValueData: "OniPlayer.mov"

; WMV
Root: HKLM; Subkey: "Software\Classes\.wmv"; ValueType: string; ValueName: ""; ValueData: "OniPlayer.wmv"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.wmv"; ValueType: string; ValueName: ""; ValueData: "OniPlayer Video File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.wmv\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe,0"
Root: HKLM; Subkey: "Software\Classes\OniPlayer.wmv\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\.wmv\OpenWithProgids"; ValueType: none; ValueName: "OniPlayer.wmv"
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".wmv"; ValueData: "OniPlayer.wmv"

; FLV
Root: HKLM; Subkey: "Software\Classes\.flv"; ValueType: string; ValueName: ""; ValueData: "OniPlayer.flv"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.flv"; ValueType: string; ValueName: ""; ValueData: "OniPlayer Video File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\OniPlayer.flv\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe,0"
Root: HKLM; Subkey: "Software\Classes\OniPlayer.flv\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\OniPlayer.exe ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\.flv\OpenWithProgids"; ValueType: none; ValueName: "OniPlayer.flv"
Root: HKLM; Subkey: "Software\OniPlayer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".flv"; ValueData: "OniPlayer.flv"

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
